server:
  port: 8090
  address: 0.0.0.0
spring:
  profiles:
    active: dev #开发模式
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: true
  mvc:
    pathmatch:
      use-suffix-pattern: false #不过滤路径
  cache:
    ehcache:
      config: classpath:cngfig/ehcache.xml
    type: ehcache
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 20000000
  aop:
    auto: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enabled: true
      protocol: smtp
      port: 465


mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  type-aliases-package: com.ft.blog.**.entity


  global-config:
    db-config:
      column-format: true
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000

logging:
  config: classpath:logback-spring.xml
app:
  upload:
    path: D:/propty/upload
    user: admin
    password: admin
    luceneIndexPath: D:/propty/upload/index

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

tv:
  url: